# Generated by Django 4.0.2 on 2022-10-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_messages',
            field=models.IntegerField(null=True),
        ),
    ]
